apiVersion: v1
kind: Service
metadata:
  name: metrics-collector-service
spec:
  selector:
    app: metrics-collector-service
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
  type: ClusterIP
