apiVersion: v1
kind: Service
metadata:
  name: incident-management-service
spec:
  selector:
    app: incident-management-service
  ports:
    - protocol: TCP
      port: 8004
      targetPort: 8004
  type: ClusterIP
