apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-ingestion-service
  labels:
    app: log-ingestion-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: log-ingestion-service
  template:
    metadata:
      labels:
        app: log-ingestion-service
    spec:
      containers:
      - name: log-ingestion-service
        image: sentinelops/log-ingestion-service:latest
        ports:
        - containerPort: 8001
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-service:9092"
