apiVersion: v1
kind: Service
metadata:
  name: log-ingestion-service
spec:
  selector:
    app: log-ingestion-service
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: ClusterIP
